export const COUNTRIES_ALPHA2 = new Map<string, string>([
    ["AD", "Andorra"],
    ["AE", "United Arab Emirates (the)"],
    ["AF", "Afghanistan"],
    ["AG", "Antigua and Barbuda"],
    ["AI", "Anguilla"],
    ["AL", "Albania"],
    ["AM", "Armenia"],
    ["AO", "Angola"],
    ["AQ", "Antarctica"],
    ["AR", "Argentina"],
    ["AS", "American Samoa"],
    ["AT", "Austria"],
    ["AU", "Australia"],
    ["AW", "Aruba"],
    ["AX", "Åland Islands"],
    ["AZ", "Azerbaijan"],
    ["BA", "Bosnia and Herzegovina"],
    ["BB", "Barbados"],
    ["BD", "Bangladesh"],
    ["BE", "Belgium"],
    ["BF", "Burkina Faso"],
    ["BG", "Bulgaria"],
    ["BH", "Bahrain"],
    ["BI", "Burundi"],
    ["BJ", "Benin"],
    ["BL", "Saint Barthélemy"],
    ["BM", "Bermuda"],
    ["BN", "Brunei Darussalam"],
    ["BO", "Bolivia (Plurinational State of)"],
    ["BQ", "Bonaire, Sint Eustatius and Saba"],
    ["BR", "Brazil"],
    ["BS", "Bahamas (the)"],
    ["BT", "Bhutan"],
    ["BV", "Bouvet Island"],
    ["BW", "Botswana"],
    ["BY", "Belarus"],
    ["BZ", "Belize"],
    ["CA", "Canada"],
    ["CC", "Cocos (Keeling) Islands (the)"],
    ["CD", "Congo (the Democratic Republic of the)"],
    ["CF", "Central African Republic (the)"],
    ["CG", "Congo (the)"],
    ["CH", "Switzerland"],
    ["CI", "Côte d'Ivoire"],
    ["CK", "Cook Islands (the)"],
    ["CL", "Chile"],
    ["CM", "Cameroon"],
    ["CN", "China"],
    ["CO", "Colombia"],
    ["CR", "Costa Rica"],
    ["CU", "Cuba"],
    ["CV", "Cabo Verde"],
    ["CW", "Curaçao"],
    ["CX", "Christmas Island"],
    ["CY", "Cyprus"],
    ["CZ", "Czechia"],
    ["DE", "Germany"],
    ["DJ", "Djibouti"],
    ["DK", "Denmark"],
    ["DM", "Dominica"],
    ["DO", "Dominican Republic (the)"],
    ["DZ", "Algeria"],
    ["EC", "Ecuador"],
    ["EE", "Estonia"],
    ["EG", "Egypt"],
    ["EH", "Western Sahara"],
    ["ER", "Eritrea"],
    ["ES", "Spain"],
    ["ET", "Ethiopia"],
    ["FI", "Finland"],
    ["FJ", "Fiji"],
    ["FK", "Falkland Islands (the) [Malvinas]"],
    ["FM", "Micronesia (Federated States of)"],
    ["FO", "Faroe Islands (the)"],
    ["FR", "France"],
    ["GA", "Gabon"],
    ["GB", "United Kingdom of Great Britain and Northern Ireland (the)"],
    ["GD", "Grenada"],
    ["GE", "Georgia"],
    ["GF", "French Guiana"],
    ["GG", "Guernsey"],
    ["GH", "Ghana"],
    ["GI", "Gibraltar"],
    ["GL", "Greenland"],
    ["GM", "Gambia (the)"],
    ["GN", "Guinea"],
    ["GP", "Guadeloupe"],
    ["GQ", "Equatorial Guinea"],
    ["GR", "Greece"],
    ["GS", "South Georgia and the South Sandwich Islands"],
    ["GT", "Guatemala"],
    ["GU", "Guam"],
    ["GW", "Guinea-Bissau"],
    ["GY", "Guyana"],
    ["HK", "Hong Kong"],
    ["HM", "Heard Island and McDonald Islands"],
    ["HN", "Honduras"],
    ["HR", "Croatia"],
    ["HT", "Haiti"],
    ["HU", "Hungary"],
    ["ID", "Indonesia"],
    ["IE", "Ireland"],
    ["IL", "Israel"],
    ["IM", "Isle of Man"],
    ["IN", "India"],
    ["IO", "British Indian Ocean Territory (the)"],
    ["IQ", "Iraq"],
    ["IR", "Iran (Islamic Republic of)"],
    ["IS", "Iceland"],
    ["IT", "Italy"],
    ["JE", "Jersey"],
    ["JM", "Jamaica"],
    ["JO", "Jordan"],
    ["JP", "Japan"],
    ["KE", "Kenya"],
    ["KG", "Kyrgyzstan"],
    ["KH", "Cambodia"],
    ["KI", "Kiribati"],
    ["KM", "Comoros (the)"],
    ["KN", "Saint Kitts and Nevis"],
    ["KP", "Korea (the Democratic People's Republic of)"],
    ["KR", "Korea (the Republic of)"],
    ["KW", "Kuwait"],
    ["KY", "Cayman Islands (the)"],
    ["KZ", "Kazakhstan"],
    ["LA", "Lao People's Democratic Republic (the)"],
    ["LB", "Lebanon"],
    ["LC", "Saint Lucia"],
    ["LI", "Liechtenstein"],
    ["LK", "Sri Lanka"],
    ["LR", "Liberia"],
    ["LS", "Lesotho"],
    ["LT", "Lithuania"],
    ["LU", "Luxembourg"],
    ["LV", "Latvia"],
    ["LY", "Libya"],
    ["MA", "Morocco"],
    ["MC", "Monaco"],
    ["MD", "Moldova (the Republic of)"],
    ["ME", "Montenegro"],
    ["MF", "Saint Martin (French part)"],
    ["MG", "Madagascar"],
    ["MH", "Marshall Islands (the)"],
    ["MK", "Republic of North Macedonia"],
    ["ML", "Mali"],
    ["MM", "Myanmar"],
    ["MN", "Mongolia"],
    ["MO", "Macao"],
    ["MP", "Northern Mariana Islands (the)"],
    ["MQ", "Martinique"],
    ["MR", "Mauritania"],
    ["MS", "Montserrat"],
    ["MT", "Malta"],
    ["MU", "Mauritius"],
    ["MV", "Maldives"],
    ["MW", "Malawi"],
    ["MX", "Mexico"],
    ["MY", "Malaysia"],
    ["MZ", "Mozambique"],
    ["NA", "Namibia"],
    ["NC", "New Caledonia"],
    ["NE", "Niger (the)"],
    ["NF", "Norfolk Island"],
    ["NG", "Nigeria"],
    ["NI", "Nicaragua"],
    ["NL", "Netherlands (the)"],
    ["NO", "Norway"],
    ["NP", "Nepal"],
    ["NR", "Nauru"],
    ["NU", "Niue"],
    ["NZ", "New Zealand"],
    ["OM", "Oman"],
    ["PA", "Panama"],
    ["PE", "Peru"],
    ["PF", "French Polynesia"],
    ["PG", "Papua New Guinea"],
    ["PH", "Philippines (the)"],
    ["PK", "Pakistan"],
    ["PL", "Poland"],
    ["PM", "Saint Pierre and Miquelon"],
    ["PN", "Pitcairn"],
    ["PR", "Puerto Rico"],
    ["PS", "Palestine, State of"],
    ["PT", "Portugal"],
    ["PW", "Palau"],
    ["PY", "Paraguay"],
    ["QA", "Qatar"],
    ["RE", "Réunion"],
    ["RO", "Romania"],
    ["RS", "Serbia"],
    ["RU", "Russian Federation (the)"],
    ["RW", "Rwanda"],
    ["SA", "Saudi Arabia"],
    ["SB", "Solomon Islands"],
    ["SC", "Seychelles"],
    ["SD", "Sudan (the)"],
    ["SE", "Sweden"],
    ["SG", "Singapore"],
    ["SH", "Saint Helena, Ascension and Tristan da Cunha"],
    ["SI", "Slovenia"],
    ["SJ", "Svalbard and Jan Mayen"],
    ["SK", "Slovakia"],
    ["SL", "Sierra Leone"],
    ["SM", "San Marino"],
    ["SN", "Senegal"],
    ["SO", "Somalia"],
    ["SR", "Suriname"],
    ["SS", "South Sudan"],
    ["ST", "Sao Tome and Principe"],
    ["SV", "El Salvador"],
    ["SX", "Sint Maarten (Dutch part)"],
    ["SY", "Syrian Arab Republic"],
    ["SZ", "Eswatini"],
    ["TC", "Turks and Caicos Islands (the)"],
    ["TD", "Chad"],
    ["TF", "French Southern Territories (the)"],
    ["TG", "Togo"],
    ["TH", "Thailand"],
    ["TJ", "Tajikistan"],
    ["TK", "Tokelau"],
    ["TL", "Timor-Leste"],
    ["TM", "Turkmenistan"],
    ["TN", "Tunisia"],
    ["TO", "Tonga"],
    ["TR", "Turkey"],
    ["TT", "Trinidad and Tobago"],
    ["TV", "Tuvalu"],
    ["TW", "Taiwan"],
    ["TZ", "Tanzania, United Republic of"],
    ["UA", "Ukraine"],
    ["UG", "Uganda"],
    ["UM", "United States Minor Outlying Islands (the)"],
    ["US", "United States of America (the)"],
    ["UY", "Uruguay"],
    ["UZ", "Uzbekistan"],
    ["VA", "Holy See (the)"],
    ["VC", "Saint Vincent and the Grenadines"],
    ["VE", "Venezuela (Bolivarian Republic of)"],
    ["VG", "Virgin Islands (British)"],
    ["VI", "Virgin Islands (U.S.)"],
    ["VN", "Viet Nam"],
    ["VU", "Vanuatu"],
    ["WF", "Wallis and Futuna"],
    ["WS", "Samoa"],
    ["YE", "Yemen"],
    ["YT", "Mayotte"],
    ["ZA", "South Africa"],
    ["ZM", "Zambia"],
    ["ZW", "Zimbabwe"]
])

export enum CountriesAlpha2 {
    AF = "AF",
    AL = "AL",
    AS = "AS",
    AD = "AD",
    AO = "AO",
    AI = "AI",
    AQ = "AQ",
    AG = "AG",
    AR = "AR",
    AM = "AM",
    AW = "AW",
    AU = "AU",
    AT = "AT",
    AZ = "AZ",
    AE = "AE",
    AX = "AX",
    BS = "BS",
    BH = "BH",
    BD = "BD",
    BB = "BB",
    BY = "BY",
    BE = "BE",
    BZ = "BZ",
    BJ = "BJ",
    BM = "BM",
    BT = "BT",
    BO = "BO",
    BQ = "BQ",
    BA = "BA",
    BW = "BW",
    BV = "BV",
    BR = "BR",
    BN = "BN",
    BG = "BG",
    BF = "BF",
    BI = "BI",
    BL = "BL",
    CV = "CV",
    CM = "CM",
    CA = "CA",
    CF = "CF",
    CL = "CL",
    CN = "CN",
    CX = "CX",
    CC = "CC",
    CO = "CO",
    CD = "CD",
    CG = "CG",
    CK = "CK",
    CR = "CR",
    CU = "CU",
    CW = "CW",
    CY = "CY",
    CZ = "CZ",
    CI = "CI",
    CH = "CH",
    DZ = "DZ",
    DK = "DK",
    DJ = "DJ",
    DM = "DM",
    DO = "DO",
    DE = "DE",
    EC = "EC",
    EG = "EG",
    ER = "ER",
    EE = "EE",
    ET = "ET",
    ES = "ES",
    EH = "EH",
    FK = "FK",
    FO = "FO",
    FJ = "FJ",
    FI = "FI",
    FR = "FR",
    FM = "FM",
    GQ = "GQ",
    GF = "GF",
    GA = "GA",
    GM = "GM",
    GE = "GE",
    GH = "GH",
    GI = "GI",
    GR = "GR",
    GL = "GL",
    GD = "GD",
    GP = "GP",
    GU = "GU",
    GT = "GT",
    GG = "GG",
    GN = "GN",
    GW = "GW",
    GY = "GY",
    GS = "GS",
    GB = "GB",
    HR = "HR",
    HT = "HT",
    HM = "HM",
    HN = "HN",
    HK = "HK",
    HU = "HU",
    IO = "IO",
    IS = "IS",
    IN = "IN",
    ID = "ID",
    IR = "IR",
    IQ = "IQ",
    IE = "IE",
    IM = "IM",
    IL = "IL",
    IT = "IT",
    JM = "JM",
    JP = "JP",
    JE = "JE",
    JO = "JO",
    KH = "KH",
    KY = "KY",
    KM = "KM",
    KZ = "KZ",
    KE = "KE",
    KI = "KI",
    KP = "KP",
    KR = "KR",
    KW = "KW",
    KG = "KG",
    KN = "KN",
    LA = "LA",
    LV = "LV",
    LB = "LB",
    LS = "LS",
    LR = "LR",
    LY = "LY",
    LI = "LI",
    LT = "LT",
    LU = "LU",
    LC = "LC",
    LK = "LK",
    MO = "MO",
    MG = "MG",
    MW = "MW",
    MY = "MY",
    MV = "MV",
    ML = "ML",
    MT = "MT",
    MH = "MH",
    MQ = "MQ",
    MR = "MR",
    MU = "MU",
    MX = "MX",
    MD = "MD",
    MC = "MC",
    MN = "MN",
    ME = "ME",
    MS = "MS",
    MA = "MA",
    MZ = "MZ",
    MM = "MM",
    MP = "MP",
    MK = "MK",
    MF = "MF",
    NA = "NA",
    NR = "NR",
    NP = "NP",
    NL = "NL",
    NC = "NC",
    NZ = "NZ",
    NI = "NI",
    NE = "NE",
    NG = "NG",
    NU = "NU",
    NF = "NF",
    NO = "NO",
    OM = "OM",
    PF = "PF",
    PK = "PK",
    PW = "PW",
    PS = "PS",
    PA = "PA",
    PG = "PG",
    PY = "PY",
    PE = "PE",
    PH = "PH",
    PN = "PN",
    PL = "PL",
    PT = "PT",
    PR = "PR",
    PM = "PM",
    QA = "QA",
    RO = "RO",
    RU = "RU",
    RW = "RW",
    RE = "RE",
    RS = "RS",
    SV = "SV",
    SZ = "SZ",
    SH = "SH",
    SM = "SM",
    ST = "ST",
    SA = "SA",
    SN = "SN",
    SC = "SC",
    SL = "SL",
    SG = "SG",
    SX = "SX",
    SK = "SK",
    SI = "SI",
    SB = "SB",
    SO = "SO",
    SS = "SS",
    SD = "SD",
    SR = "SR",
    SJ = "SJ",
    SE = "SE",
    SY = "SY",
    TD = "TD",
    TF = "TF",
    TW = "TW",
    TJ = "TJ",
    TZ = "TZ",
    TH = "TH",
    TL = "TL",
    TG = "TG",
    TK = "TK",
    TO = "TO",
    TT = "TT",
    TN = "TN",
    TR = "TR",
    TM = "TM",
    TC = "TC",
    TV = "TV",
    UG = "UG",
    UA = "UA",
    UM = "UM",
    US = "US",
    UY = "UY",
    UZ = "UZ",
    VA = "VA",
    VC = "VC",
    VU = "VU",
    VE = "VE",
    VN = "VN",
    VG = "VG",
    VI = "VI",
    WS = "WS",
    WF = "WF",
    YT = "YT",
    YE = "YE",
    ZA = "ZA",
    ZM = "ZM",
    ZW = "ZW"
}
