export * from "./AbstractCountryValue"
export * from "./AbstractDataURIValue"
export * from "./AbstractEMailAddressValue"
export * from "./AbstractHEXColorValue"
export * from "./AbstractLanguageValue"
export * from "./AbstractNationalityValue"
export * from "./AbstractPhoneNumberValue"
export * from "./AbstractURLValue"
