name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container: jssoft/node_browsertests
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install jq -y
      - run: bash .ci/build.sh
      - run: bash .ci/test.sh
      - run: bash .ci/publish.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
