name: Version Check

on:
  pull_request:
    branches: [main]

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install jq -y
      - run: |
          HEAD_REF=${{ github.head_ref }}

          if [[ $HEAD_REF =~ ^release/.*$ ]]; then
            echo "Skipping version check for release branch"
            exit 0
          fi

          VERSION=$(jq .version package.json -cr)

          case "$VERSION" in
          *-alpha*) echo "pre-id -alpha is not allowed when merging from $HEAD_REF" && exit 1 ;;
          *-beta*) echo "pre-id -beta is not allowed when merging from $HEAD_REF" && exit 1 ;;
          *-rc*) echo "pre-id -rc is not allowed when merging from $HEAD_REF" && exit 1 ;;
          *) exit 0 ;;
          esac
