name: Version Check

on:
  pull_request:
    branches: [main]

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install jq -y
      - run: |
          if [[ ${{ github.head_ref }} =~ ^release/.*$ ]]; then
            echo "Skipping version check for release branch"
            exit 0
          fi

          VERSION=$(jq .version package.json -cr)

          case "$VERSION" in
          *-alpha*) exit 1 ;;
          *-beta*) exit 1 ;;
          *-rc*) exit 1 ;;
          *) exit 0 ;;
          esac
